### ISSUE TITLE
Question about word embedding 

### ISSUE THREAD

**Issue by harukaza** [PhoebusSi/SAR#1]
I confuse about the embedding in your paper.  _LXMERT separately encodes image and caption text in two streams_ in paper 3.2.3. 1. The processed caption are word or word embedding？
2. _L = LV E + Lssl_ when change SSL to LMH, the loss of ssl may be the loss of LMH？

**Comment by PhoebusSi** [comment]
A1:  A sequence of word ids. The caption is processed by the tokenizer of Lxmert( which is identical to BERT tokenizer). This tokenzer can transfer the caption into a sequence of word ids which is (a part of) the input of LXMERT. You can refer https://huggingface.co/transformers/model_doc/lxmert.html?highlight=lxmert for more implementation detail of LXMERT.
A2 : Yes.
