### ISSUE TITLE
When executing the proprecess.py file, I get an error

### ISSUE THREAD

**Issue by cunese-debug** [PhoebusSi/SAR#4]
![image](https://user-images.githubusercontent.com/53068386/171618008-839d42fe-13c4-4921-9e2a-978ddbc89c16.png)
**_csv.Error: line contains NUL_**
I don't know why, when I execute the preprocess.py file, this kind of problem occurs, is there something wrong with my data set

**Comment by PhoebusSi** [comment]
Sorry for the late response. 
This may be because the JSON file is corrupted.
