### ISSUE TITLE
Guild to generate the `train_top20_candidates.json`

### ISSUE THREAD

**Issue by baileytrang** [PhoebusSi/SAR#5]
Hi authors,
@PhoebusSi 

First of all, thank you for your great work.

Next, I would like to ask for more detailed instruction for generating the `train_top20_candidates.json` and `test_top20_candidates.json`.

Could you please help me  :pray:

Many thanks!

**Comment by PhoebusSi** [comment]
We directly adopts SSL's model in our candidate answer selection module. 

So you can first implement SSL according to its instructions at https://github.com/CrossmodalGroup/SSL-VQA. 

Then, you need to evaluate SSL model on VQA-CP v2's training set and test set, respectively. Before that, you need to replace its ```evaluate()''' function (in train.py) with our  evaluate() function at https://github.com/PhoebusSi/SAR/blob/master/CAS_scripts/Candidate_Answers_Selector.py, where we added the function of saving the top20 candidate in json files.

**Comment by PhoebusSi** [comment]
It is worth mentioning that the ```VQAFeatureDataset''' class in SSL may be inconsistent with ours. Therefore, for simplicity, you can use the class at https://github.com/PhoebusSi/SAR/blob/master/CAS_scripts/CAS_dataset_vqacp.py to replace that of SSL.

**Comment by baileytrang** [comment]
Thank you for your quick response!

What I did from your instruction:
```
1. git clone https://github.com/CrossmodalGroup/SSL-VQA.git
```
2. Copy `compute_TopKscore_with_logits()`, `evaluate()` from https://github.com/PhoebusSi/SAR/blob/master/CAS_scripts/Candidate_Answers_Selector.py to https://github.com/CrossmodalGroup/SSL-VQA/blob/master/train.py
3. Replace https://github.com/CrossmodalGroup/SSL-VQA/blob/master/dataset_vqacp.py#L149 by https://github.com/PhoebusSi/SAR/blob/master/CAS_scripts/CAS_dataset_vqacp.py#L23 
4. 
```
python test.py --checkpoint_path path/to/https://github.com/PhoebusSi/SAR/tree/master/data4VE/offline-QTD_model.pth
```


Then I get:
```
Traceback (most recent call last):
  File "SSL-VQA/test.py", line 83, in <module>
    model.load_state_dict(model_data.get('model_state', model_data))
  File "/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
        Missing key(s) in state_dict: "module.w_emb.emb.weight", "module.q_emb.rnn.weight_ih_l0", "module.q_emb.rnn.weight_hh_l0", "module.q_emb.rnn.bias_ih_l0", "module.q_emb.rnn.bias_hh_l0", "module.q_net.main.0.bias", "module.q_net.main.0.weight_g", "module.q_net.main.0.weight_v", "module.gv_net.main.0.bias", "module.gv_net.main.0.weight_g", "module.gv_net.main.0.weight_v", "module.gv_att_1.v_proj.main.0.bias", "module.gv_att_1.v_proj.main.0.weight_g", "module.gv_att_1.v_proj.main.0.weight_v", "module.gv_att_1.q_proj.main.0.bias", "module.gv_att_1.q_proj.main.0.weight_g", "module.gv_att_1.q_proj.main.0.weight_v", "module.gv_att_1.nonlinear.main.0.bias", "module.gv_att_1.nonlinear.main.0.weight_g", "module.gv_att_1.nonlinear.main.0.weight_v", "module.gv_att_1.linear.bias", "module.gv_att_1.linear.weight_g", "module.gv_att_1.linear.weight_v", "module.gv_att_2.v_proj.main.0.bias", "module.gv_att_2.v_proj.main.0.weight_g", "module.gv_att_2.v_proj.main.0.weight_v", "module.gv_att_2.q_proj.main.0.bias", "module.gv_att_2.q_proj.main.0.weight_g", "module.gv_att_2.q_proj.main.0.weight_v", "module.gv_att_2.nonlinear.main.0.bias", "module.gv_att_2.nonlinear.main.0.weight_g", "module.gv_att_2.nonlinear.main.0.weight_v", "module.gv_att_2.linear.bias", "module.gv_att_2.linear.weight_g", "module.gv_att_2.linear.weight_v", "module.classifier.main.0.bias", "module.classifier.main.0.weight_g", "module.classifier.main.0.weight_v", "module.classifier.main.3.bias", "module.classifier.main.3.weight_g", "module.classifier.main.3.weight_v", "module.normal.running_mean", "module.normal.running_var". 
        Unexpected key(s) in state_dict: "w_emb.emb.weight", "q_emb.rnn.weight_ih_l0", "q_emb.rnn.weight_hh_l0", "q_emb.rnn.bias_ih_l0", "q_emb.rnn.bias_hh_l0", "q_net.main.0.bias", "q_net.main.0.weight_g", "q_net.main.0.weight_v", "classifier.main.0.bias", "classifier.main.0.weight_g", "classifier.main.0.weight_v", "classifier.main.3.bias", "classifier.main.3.weight_g", "classifier.main.3.weight_v", "normal.running_mean", "normal.running_var", "normal.num_batches_tracked". 
```


Could you please help me to have a look at it. Thank you! 🙏

**Comment by PhoebusSi** [comment]
The pipeline is as follows:
1. You need to modify the SSL's code as mentioned before, where you have done well. 
2. Then to train an SSL model and save its checkpoint first. (Follow the instructions at https://github.com/CrossmodalGroup/SSL-VQA)
3. Next, when evaluating an SSL model (to obtain Top20 candidates for the training set and test set, respectively), you should load the SSL model checkpoint instead of 'offline-QTD_model.pth'. (Still follow the instructions at https://github.com/CrossmodalGroup/SSL-VQA)
4. Only when you have reached the top-20 candidates JSON files can you start training your own SAR models (follow the instructions at https://github.com/PhoebusSi/SAR).
5. Finally, when evaluating SAR models, you can load the offline-QTD_model.pth for the question type detector module, and the saved SAR checkpoint for our final model.

You'd better read the paper&code to understand the overall process.

**Comment by baileytrang** [comment]
I got the situation now.
It worked fine.

Thank you! 🙏
